all:
  children:
    ubuntu_vms:
      hosts:
        cloudflare-tunnel-host: { ansible_host: 192.168.2.9 }
        bare-metal-docker: { ansible_host: 192.168.2.96 }
        xoa: { ansible_host: 192.168.2.94 }
      vars:
        ansible_user: john
        ansible_become: yes

    k8s_nodes:
      hosts:
        k8s-dev: { ansible_host: 192.168.2.92 }
        k8s-prod: { ansible_host: 192.168.2.95 }
      vars:
        ansible_user: user
        ansible_become: yes
